name:                trigger
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/trigger#readme
license:             MIT
author:              Kostiantyn Rybnikov
maintainer:          Kostiantyn Rybnikov <k-bx@k-bx.com>
copyright:           2019 Kostiantyn Rybnikov
category:            CommandLine
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - async
  - process
  - fsnotify
  - unix
  - filepath

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -threaded
  - -rtsopts

executables:
  trigger:
    source-dirs:      src
    main:             Main.hs
